### PR TITLE
Dani project

### PR DESCRIPTION
**Pull request by danhuiZ**
Try project report #2 again as the previous one did not include my own version of environment.yml in folder

### CODE REVIEW

**Comment by jzf2101** [comment]
There are errors in your enviornment file.

**Review by jzf2101 — CHANGES_REQUESTED** [review]
There are errors in your enviornment file.

**Comment by danhuiZ** [comment]
I used additional packages so I will need customized travis test...! Thank you.

**Comment by jzf2101** [comment]
The test is breaking because your PR alters the environment file.  I cannot accept the submission if the environment file is changed. see https://github.com/em212/applied_ds/pull/168/files

**Pull request closed without merging**
