### PR TITLE
test the io_hw.py file

### PR DESCRIPTION
**Pull request by rshi01**

### CODE REVIEW

**Comment by jzf2101** [comment]
This is only a sample of your dataset?

**Comment by rshi01** [comment]
> This is only a sample of your dataset?

Yes, the origin dataset is too big to upload to GitHub.

**Review by jzf2101 — APPROVED** [review]

**Comment by jzf2101** [comment]
This data exists online and can be loaded from a URL

**Comment by rshi01** [comment]
I try to use url and pull the update, but there is this error. I run locally and the columns are equal. Would you mind helping me see where is wrong?
E     File "/home/travis/build/em212/applied_ds/test_io_hw.py", line 20
E       assert len(df.columns) == len(head_df.columns)
E            ^
E   SyntaxError: invalid syntax

**Pull request closed without merging**
